package com.hcmus.model.pojo;
// Generated Nov 29, 2016 3:35:54 PM by Hibernate Tools 3.5.0.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Card generated by hbm2java
 */
public class Card implements java.io.Serializable {

	private String accountNumber;
	private String cardTypeCode;
	private CardType cardType;
	private String fullName;
	private Date expirationDate;
	private String firstTwelveAccountNumber;
	private Set<Retrival> retrivals = new HashSet<Retrival>(0);
	private Set<TransactionDetail> transactionDetails = new HashSet<TransactionDetail>(0);

	public Card() {
	}


	public Card(String accountNumber, CardType cardType, String cardTypeCode, String fullName, Date expirationDate,
			String firstTwelveAccountNumber, Set<Retrival> retrivals, Set<TransactionDetail> transactionDetails) {
		this.accountNumber = accountNumber;
		this.cardType = cardType;
		this.cardTypeCode = cardTypeCode;
		this.fullName = fullName;
		this.expirationDate = expirationDate;
		this.firstTwelveAccountNumber = firstTwelveAccountNumber;
		this.retrivals = retrivals;
		this.transactionDetails = transactionDetails;
	}

	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	public CardType getCardType() {
		return this.cardType;
	}

	public void setCardType(CardType cardType) {
		this.cardType = ORMUtils.initializeAndUnproxy(cardType);
	}
	public String getCardTypeCode() {
		return cardTypeCode;
	}


	public void setCardTypeCode(String cardTypeCode) {
		this.cardTypeCode = cardTypeCode;
	}
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	public String getFirstTwelveAccountNumber() {
		return this.firstTwelveAccountNumber;
	}

	public void setFirstTwelveAccountNumber(String firstTwelveAccountNumber) {
		this.firstTwelveAccountNumber = firstTwelveAccountNumber;
	}

	public Set<Retrival> getRetrivals() {
		return this.retrivals;
	}

	public void setRetrivals(Set<Retrival> retrivals) {
		this.retrivals = ORMUtils.initializeAndUnproxy(retrivals);
	}

	public Set<TransactionDetail> getTransactionDetails() {
		return this.transactionDetails;
	}

	public void setTransactionDetails(Set<TransactionDetail> transactionDetails) {
		this.transactionDetails = ORMUtils.initializeAndUnproxy(transactionDetails);
	}

}
