package com.hcmus.model.pojo;


import java.util.HashSet;
//import java.io.String;
//import java.util.HashSet;
import java.util.Set;

import org.springframework.transaction.annotation.Transactional;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * City generated by hbm2java
 */
@Transactional
public class City implements java.io.Serializable {

	private String CityCode;
	private String RegionCode;
	private String CityName;
	private Region REGION;
	private Set<Merchant> MERCHANTS = new HashSet<Merchant>(0);
	private Set<Agent> AGENTS = new HashSet<Agent>(0);

	public City() {
	}

	public City(String cityCode,String regionCode, Region region, String cityName, Set<Merchant> merchants, Set<Agent> agents) {
		this.CityCode = cityCode;
		this.RegionCode = regionCode;
		this.CityName = cityName;
		this.REGION = region;
		this.MERCHANTS = merchants;
		this.AGENTS = agents;
	}

	@JsonProperty("CityCode")
	public String getCityCode() {
		return this.CityCode;
	}

	public void setCityCode(String cityCode) {
		this.CityCode = cityCode;
	}
	
	@JsonProperty("RegionCode")
	public String getRegionCode() {
		return RegionCode;
	}

	public void setRegionCode(String regionCode) {
		this.RegionCode = regionCode;
	}

	@JsonProperty("CityName")
	public String getCityName() {
		return this.CityName;
	}

	public void setCityName(String cityName) {
		this.CityName = cityName;
	}
	
	@JsonProperty("MERCHANTS")
	public Set<Merchant> getMerchants() {
		return this.MERCHANTS;
	}

	public void setMerchants(Set<Merchant> merchants) {
		this.MERCHANTS = ORMUtils.initializeAndUnproxy(merchants);
	}
	
	@JsonProperty("AGENTS")
	public Set<Agent> getAgents() {
		return this.AGENTS;
	}

	public void setAgents(Set<Agent> agents) {
		this.AGENTS = ORMUtils.initializeAndUnproxy(agents);
	}
	
	@JsonProperty("REGION")
	public Region getRegion() {
		return this.REGION;
	}

	public void setRegion(Region region) {
		this.REGION = ORMUtils.initializeAndUnproxy(region);
	}
	
}
