package com.hcmus.model.pojo;


import java.util.HashSet;
//import java.io.String;
//import java.util.HashSet;
import java.util.Set;

import org.springframework.transaction.annotation.Transactional;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * City generated by hbm2java
 */
@Transactional
public class City implements java.io.Serializable {

	private String cityCode;
	private String regionCode;
	private String cityName;
	private Region region;
	private Set<Merchant> merchants = new HashSet<Merchant>(0);
	private Set<Agent> agents = new HashSet<Agent>(0);

	public City() {
	}

	public City(String cityCode,String regionCode, Region region, String cityName, Set<Merchant> merchants, Set<Agent> agents) {
		this.cityCode = cityCode;
		this.regionCode = regionCode;
		this.cityName = cityName;
		this.region = region;
		this.merchants = merchants;
		this.agents = agents;
	}

	public String getCityCode() {
		return this.cityCode;
	}

	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}
	public String getRegionCode() {
		return regionCode;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}

	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}
	
	public Set<Merchant> getMerchants() {
		return this.merchants;
	}

	public void setMerchants(Set<Merchant> merchants) {
		this.merchants = ORMUtils.initializeAndUnproxy(merchants);
	}
	
	public Set<Agent> getAgents() {
		return this.agents;
	}

	public void setAgents(Set<Agent> agents) {
		this.agents = ORMUtils.initializeAndUnproxy(agents);
	}
	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = ORMUtils.initializeAndUnproxy(region);
	}
	
}
