package com.hcmus.model.pojo;
// Generated Nov 29, 2016 3:35:54 PM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * MerchantSummaryDaily generated by hbm2java
 */
public class MerchantSummaryDaily implements java.io.Serializable {

	//private MerchantSummaryDailyId id;
	private Date reportDate;
	private String merchantCode;
	private BigDecimal saleAmount;
	private Integer saleCount;
	private BigDecimal returnAmount;
	private Integer returnCount;
	private BigDecimal netAmount;
	private Integer transactionCount;
	private BigDecimal keyedAmount;
	private Integer keyedCount;
	private BigDecimal keyedReturnAmount;
	private Integer keyedReturnCount;
	private BigDecimal keyedNetAmount;
	private Integer keyedTransactionCount;
	private BigDecimal foreignCardAmount;
	private Integer foreignCardCount;
	private BigDecimal foreignCardReturnAmount;
	private Integer foreignCardReturnCount;
	private BigDecimal foreignCardNetAmount;
	private Integer foreignCardTransactionCount;
	private BigDecimal debitCardAmount;
	private Integer debitCardCount;
	private BigDecimal debitCardReturnAmount;
	private Integer debitCardReturnCount;
	private BigDecimal debitCardNetAmount;
	private Integer debitCardTransactionCount;
	private BigDecimal visaCardAmount;
	private Integer visaCardCount;
	private BigDecimal visaCardReturnAmount;
	private Integer visaCardReturnCount;
	private BigDecimal visaCardNetAmount;
	private Integer visaCardTransactionCount;
	private BigDecimal discoverCardAmount;
	private Integer discoverCardCount;
	private BigDecimal discoverCardReturnAmount;
	private Integer discoverCardReturnCount;
	private BigDecimal discoverCardNetAmount;
	private Integer discoverCardTransactionCount;
	private BigDecimal masterCardAmount;
	private Integer masterCardCount;
	private BigDecimal masterCardReturnAmount;
	private Integer masterCardReturnCount;
	private BigDecimal masterCardNetAmount;
	private Integer masterCardTransactionCount;
	private BigDecimal americanExpressAmount;
	private Integer americanExpressCount;
	private BigDecimal americanExpressReturnAmount;
	private Integer americanExpressReturnCount;
	private BigDecimal americanExpressNetAmount;
	private Integer americanExpressTransactionCount;
	private BigDecimal otherCardAmount;
	private Integer otherCardCount;
	private BigDecimal otherCardReturnAmount;
	private Integer otherCardReturnCount;
	private BigDecimal otherCardNetAmount;
	private Integer otherCardTransactionCount;
	private String regionCode;
	private String merchantType;
	private String agentCode;

	public MerchantSummaryDaily() {
	}

	

	public MerchantSummaryDaily(Date reportDate, String merchantCode, BigDecimal saleAmount, Integer saleCount,
			BigDecimal returnAmount, Integer returnCount, BigDecimal netAmount, Integer transactionCount,
			BigDecimal keyedAmount, Integer keyedCount, BigDecimal keyedReturnAmount, Integer keyedReturnCount,
			BigDecimal keyedNetAmount, Integer keyedTransactionCount, BigDecimal foreignCardAmount,
			Integer foreignCardCount, BigDecimal foreignCardReturnAmount, Integer foreignCardReturnCount,
			BigDecimal foreignCardNetAmount, Integer foreignCardTransactionCount, BigDecimal debitCardAmount,
			Integer debitCardCount, BigDecimal debitCardReturnAmount, Integer debitCardReturnCount,
			BigDecimal debitCardNetAmount, Integer debitCardTransactionCount, BigDecimal visaCardAmount,
			Integer visaCardCount, BigDecimal visaCardReturnAmount, Integer visaCardReturnCount,
			BigDecimal visaCardNetAmount, Integer visaCardTransactionCount, BigDecimal discoverCardAmount,
			Integer discoverCardCount, BigDecimal discoverCardReturnAmount, Integer discoverCardReturnCount,
			BigDecimal discoverCardNetAmount, Integer discoverCardTransactionCount, BigDecimal masterCardAmount,
			Integer masterCardCount, BigDecimal masterCardReturnAmount, Integer masterCardReturnCount,
			BigDecimal masterCardNetAmount, Integer masterCardTransactionCount, BigDecimal americanExpressAmount,
			Integer americanExpressCount, BigDecimal americanExpressReturnAmount, Integer americanExpressReturnCount,
			BigDecimal americanExpressNetAmount, Integer americanExpressTransactionCount, BigDecimal otherCardAmount,
			Integer otherCardCount, BigDecimal otherCardReturnAmount, Integer otherCardReturnCount,
			BigDecimal otherCardNetAmount, Integer otherCardTransactionCount, String regionCode, String merchantType,
			String agentCode) {
		//this.id = id;
		this.reportDate = reportDate;
		this.merchantCode = merchantCode;
		this.saleAmount = saleAmount;
		this.saleCount = saleCount;
		this.returnAmount = returnAmount;
		this.returnCount = returnCount;
		this.netAmount = netAmount;
		this.transactionCount = transactionCount;
		this.keyedAmount = keyedAmount;
		this.keyedCount = keyedCount;
		this.keyedReturnAmount = keyedReturnAmount;
		this.keyedReturnCount = keyedReturnCount;
		this.keyedNetAmount = keyedNetAmount;
		this.keyedTransactionCount = keyedTransactionCount;
		this.foreignCardAmount = foreignCardAmount;
		this.foreignCardCount = foreignCardCount;
		this.foreignCardReturnAmount = foreignCardReturnAmount;
		this.foreignCardReturnCount = foreignCardReturnCount;
		this.foreignCardNetAmount = foreignCardNetAmount;
		this.foreignCardTransactionCount = foreignCardTransactionCount;
		this.debitCardAmount = debitCardAmount;
		this.debitCardCount = debitCardCount;
		this.debitCardReturnAmount = debitCardReturnAmount;
		this.debitCardReturnCount = debitCardReturnCount;
		this.debitCardNetAmount = debitCardNetAmount;
		this.debitCardTransactionCount = debitCardTransactionCount;
		this.visaCardAmount = visaCardAmount;
		this.visaCardCount = visaCardCount;
		this.visaCardReturnAmount = visaCardReturnAmount;
		this.visaCardReturnCount = visaCardReturnCount;
		this.visaCardNetAmount = visaCardNetAmount;
		this.visaCardTransactionCount = visaCardTransactionCount;
		this.discoverCardAmount = discoverCardAmount;
		this.discoverCardCount = discoverCardCount;
		this.discoverCardReturnAmount = discoverCardReturnAmount;
		this.discoverCardReturnCount = discoverCardReturnCount;
		this.discoverCardNetAmount = discoverCardNetAmount;
		this.discoverCardTransactionCount = discoverCardTransactionCount;
		this.masterCardAmount = masterCardAmount;
		this.masterCardCount = masterCardCount;
		this.masterCardReturnAmount = masterCardReturnAmount;
		this.masterCardReturnCount = masterCardReturnCount;
		this.masterCardNetAmount = masterCardNetAmount;
		this.masterCardTransactionCount = masterCardTransactionCount;
		this.americanExpressAmount = americanExpressAmount;
		this.americanExpressCount = americanExpressCount;
		this.americanExpressReturnAmount = americanExpressReturnAmount;
		this.americanExpressReturnCount = americanExpressReturnCount;
		this.americanExpressNetAmount = americanExpressNetAmount;
		this.americanExpressTransactionCount = americanExpressTransactionCount;
		this.otherCardAmount = otherCardAmount;
		this.otherCardCount = otherCardCount;
		this.otherCardReturnAmount = otherCardReturnAmount;
		this.otherCardReturnCount = otherCardReturnCount;
		this.otherCardNetAmount = otherCardNetAmount;
		this.otherCardTransactionCount = otherCardTransactionCount;
		this.regionCode = regionCode;
		this.merchantType = merchantType;
		this.agentCode = agentCode;
	}
	public Date getReportDate() {
		return reportDate;
	}

	public void setReportDate(Date reportDate) {
		this.reportDate = reportDate;
	}

	public String getMerchantCode() {
		return merchantCode;
	}

	public void setMerchantCode(String merchantCode) {
		this.merchantCode = merchantCode;
	}
	/*
	public MerchantSummaryDailyId getId() {
		return this.id;
	}

	public void setId(MerchantSummaryDailyId id) {
		this.id = id;
	}
	*/
	public BigDecimal getSaleAmount() {
		return this.saleAmount;
	}

	public void setSaleAmount(BigDecimal saleAmount) {
		this.saleAmount = saleAmount;
	}

	public Integer getSaleCount() {
		return this.saleCount;
	}

	public void setSaleCount(Integer saleCount) {
		this.saleCount = saleCount;
	}

	public BigDecimal getReturnAmount() {
		return this.returnAmount;
	}

	public void setReturnAmount(BigDecimal returnAmount) {
		this.returnAmount = returnAmount;
	}

	public Integer getReturnCount() {
		return this.returnCount;
	}

	public void setReturnCount(Integer returnCount) {
		this.returnCount = returnCount;
	}

	public BigDecimal getNetAmount() {
		return this.netAmount;
	}

	public void setNetAmount(BigDecimal netAmount) {
		this.netAmount = netAmount;
	}

	public Integer getTransactionCount() {
		return this.transactionCount;
	}

	public void setTransactionCount(Integer transactionCount) {
		this.transactionCount = transactionCount;
	}

	public BigDecimal getKeyedAmount() {
		return this.keyedAmount;
	}

	public void setKeyedAmount(BigDecimal keyedAmount) {
		this.keyedAmount = keyedAmount;
	}

	public Integer getKeyedCount() {
		return this.keyedCount;
	}

	public void setKeyedCount(Integer keyedCount) {
		this.keyedCount = keyedCount;
	}

	public BigDecimal getKeyedReturnAmount() {
		return this.keyedReturnAmount;
	}

	public void setKeyedReturnAmount(BigDecimal keyedReturnAmount) {
		this.keyedReturnAmount = keyedReturnAmount;
	}

	public Integer getKeyedReturnCount() {
		return this.keyedReturnCount;
	}

	public void setKeyedReturnCount(Integer keyedReturnCount) {
		this.keyedReturnCount = keyedReturnCount;
	}

	public BigDecimal getKeyedNetAmount() {
		return this.keyedNetAmount;
	}

	public void setKeyedNetAmount(BigDecimal keyedNetAmount) {
		this.keyedNetAmount = keyedNetAmount;
	}

	public Integer getKeyedTransactionCount() {
		return this.keyedTransactionCount;
	}

	public void setKeyedTransactionCount(Integer keyedTransactionCount) {
		this.keyedTransactionCount = keyedTransactionCount;
	}

	public BigDecimal getForeignCardAmount() {
		return this.foreignCardAmount;
	}

	public void setForeignCardAmount(BigDecimal foreignCardAmount) {
		this.foreignCardAmount = foreignCardAmount;
	}

	public Integer getForeignCardCount() {
		return this.foreignCardCount;
	}

	public void setForeignCardCount(Integer foreignCardCount) {
		this.foreignCardCount = foreignCardCount;
	}

	public BigDecimal getForeignCardReturnAmount() {
		return this.foreignCardReturnAmount;
	}

	public void setForeignCardReturnAmount(BigDecimal foreignCardReturnAmount) {
		this.foreignCardReturnAmount = foreignCardReturnAmount;
	}

	public Integer getForeignCardReturnCount() {
		return this.foreignCardReturnCount;
	}

	public void setForeignCardReturnCount(Integer foreignCardReturnCount) {
		this.foreignCardReturnCount = foreignCardReturnCount;
	}

	public BigDecimal getForeignCardNetAmount() {
		return this.foreignCardNetAmount;
	}

	public void setForeignCardNetAmount(BigDecimal foreignCardNetAmount) {
		this.foreignCardNetAmount = foreignCardNetAmount;
	}

	public Integer getForeignCardTransactionCount() {
		return this.foreignCardTransactionCount;
	}

	public void setForeignCardTransactionCount(Integer foreignCardTransactionCount) {
		this.foreignCardTransactionCount = foreignCardTransactionCount;
	}

	public BigDecimal getDebitCardAmount() {
		return this.debitCardAmount;
	}

	public void setDebitCardAmount(BigDecimal debitCardAmount) {
		this.debitCardAmount = debitCardAmount;
	}

	public Integer getDebitCardCount() {
		return this.debitCardCount;
	}

	public void setDebitCardCount(Integer debitCardCount) {
		this.debitCardCount = debitCardCount;
	}

	public BigDecimal getDebitCardReturnAmount() {
		return this.debitCardReturnAmount;
	}

	public void setDebitCardReturnAmount(BigDecimal debitCardReturnAmount) {
		this.debitCardReturnAmount = debitCardReturnAmount;
	}

	public Integer getDebitCardReturnCount() {
		return this.debitCardReturnCount;
	}

	public void setDebitCardReturnCount(Integer debitCardReturnCount) {
		this.debitCardReturnCount = debitCardReturnCount;
	}

	public BigDecimal getDebitCardNetAmount() {
		return this.debitCardNetAmount;
	}

	public void setDebitCardNetAmount(BigDecimal debitCardNetAmount) {
		this.debitCardNetAmount = debitCardNetAmount;
	}

	public Integer getDebitCardTransactionCount() {
		return this.debitCardTransactionCount;
	}

	public void setDebitCardTransactionCount(Integer debitCardTransactionCount) {
		this.debitCardTransactionCount = debitCardTransactionCount;
	}

	public BigDecimal getVisaCardAmount() {
		return this.visaCardAmount;
	}

	public void setVisaCardAmount(BigDecimal visaCardAmount) {
		this.visaCardAmount = visaCardAmount;
	}

	public Integer getVisaCardCount() {
		return this.visaCardCount;
	}

	public void setVisaCardCount(Integer visaCardCount) {
		this.visaCardCount = visaCardCount;
	}

	public BigDecimal getVisaCardReturnAmount() {
		return this.visaCardReturnAmount;
	}

	public void setVisaCardReturnAmount(BigDecimal visaCardReturnAmount) {
		this.visaCardReturnAmount = visaCardReturnAmount;
	}

	public Integer getVisaCardReturnCount() {
		return this.visaCardReturnCount;
	}

	public void setVisaCardReturnCount(Integer visaCardReturnCount) {
		this.visaCardReturnCount = visaCardReturnCount;
	}

	public BigDecimal getVisaCardNetAmount() {
		return this.visaCardNetAmount;
	}

	public void setVisaCardNetAmount(BigDecimal visaCardNetAmount) {
		this.visaCardNetAmount = visaCardNetAmount;
	}

	public Integer getVisaCardTransactionCount() {
		return this.visaCardTransactionCount;
	}

	public void setVisaCardTransactionCount(Integer visaCardTransactionCount) {
		this.visaCardTransactionCount = visaCardTransactionCount;
	}

	public BigDecimal getDiscoverCardAmount() {
		return this.discoverCardAmount;
	}

	public void setDiscoverCardAmount(BigDecimal discoverCardAmount) {
		this.discoverCardAmount = discoverCardAmount;
	}

	public Integer getDiscoverCardCount() {
		return this.discoverCardCount;
	}

	public void setDiscoverCardCount(Integer discoverCardCount) {
		this.discoverCardCount = discoverCardCount;
	}

	public BigDecimal getDiscoverCardReturnAmount() {
		return this.discoverCardReturnAmount;
	}

	public void setDiscoverCardReturnAmount(BigDecimal discoverCardReturnAmount) {
		this.discoverCardReturnAmount = discoverCardReturnAmount;
	}

	public Integer getDiscoverCardReturnCount() {
		return this.discoverCardReturnCount;
	}

	public void setDiscoverCardReturnCount(Integer discoverCardReturnCount) {
		this.discoverCardReturnCount = discoverCardReturnCount;
	}

	public BigDecimal getDiscoverCardNetAmount() {
		return this.discoverCardNetAmount;
	}

	public void setDiscoverCardNetAmount(BigDecimal discoverCardNetAmount) {
		this.discoverCardNetAmount = discoverCardNetAmount;
	}

	public Integer getDiscoverCardTransactionCount() {
		return this.discoverCardTransactionCount;
	}

	public void setDiscoverCardTransactionCount(Integer discoverCardTransactionCount) {
		this.discoverCardTransactionCount = discoverCardTransactionCount;
	}

	public BigDecimal getMasterCardAmount() {
		return this.masterCardAmount;
	}

	public void setMasterCardAmount(BigDecimal masterCardAmount) {
		this.masterCardAmount = masterCardAmount;
	}

	public Integer getMasterCardCount() {
		return this.masterCardCount;
	}

	public void setMasterCardCount(Integer masterCardCount) {
		this.masterCardCount = masterCardCount;
	}

	public BigDecimal getMasterCardReturnAmount() {
		return this.masterCardReturnAmount;
	}

	public void setMasterCardReturnAmount(BigDecimal masterCardReturnAmount) {
		this.masterCardReturnAmount = masterCardReturnAmount;
	}

	public Integer getMasterCardReturnCount() {
		return this.masterCardReturnCount;
	}

	public void setMasterCardReturnCount(Integer masterCardReturnCount) {
		this.masterCardReturnCount = masterCardReturnCount;
	}

	public BigDecimal getMasterCardNetAmount() {
		return this.masterCardNetAmount;
	}

	public void setMasterCardNetAmount(BigDecimal masterCardNetAmount) {
		this.masterCardNetAmount = masterCardNetAmount;
	}

	public Integer getMasterCardTransactionCount() {
		return this.masterCardTransactionCount;
	}

	public void setMasterCardTransactionCount(Integer masterCardTransactionCount) {
		this.masterCardTransactionCount = masterCardTransactionCount;
	}

	public BigDecimal getAmericanExpressAmount() {
		return this.americanExpressAmount;
	}

	public void setAmericanExpressAmount(BigDecimal americanExpressAmount) {
		this.americanExpressAmount = americanExpressAmount;
	}

	public Integer getAmericanExpressCount() {
		return this.americanExpressCount;
	}

	public void setAmericanExpressCount(Integer americanExpressCount) {
		this.americanExpressCount = americanExpressCount;
	}

	public BigDecimal getAmericanExpressReturnAmount() {
		return this.americanExpressReturnAmount;
	}

	public void setAmericanExpressReturnAmount(BigDecimal americanExpressReturnAmount) {
		this.americanExpressReturnAmount = americanExpressReturnAmount;
	}

	public Integer getAmericanExpressReturnCount() {
		return this.americanExpressReturnCount;
	}

	public void setAmericanExpressReturnCount(Integer americanExpressReturnCount) {
		this.americanExpressReturnCount = americanExpressReturnCount;
	}

	public BigDecimal getAmericanExpressNetAmount() {
		return this.americanExpressNetAmount;
	}

	public void setAmericanExpressNetAmount(BigDecimal americanExpressNetAmount) {
		this.americanExpressNetAmount = americanExpressNetAmount;
	}

	public Integer getAmericanExpressTransactionCount() {
		return this.americanExpressTransactionCount;
	}

	public void setAmericanExpressTransactionCount(Integer americanExpressTransactionCount) {
		this.americanExpressTransactionCount = americanExpressTransactionCount;
	}

	public BigDecimal getOtherCardAmount() {
		return this.otherCardAmount;
	}

	public void setOtherCardAmount(BigDecimal otherCardAmount) {
		this.otherCardAmount = otherCardAmount;
	}

	public Integer getOtherCardCount() {
		return this.otherCardCount;
	}

	public void setOtherCardCount(Integer otherCardCount) {
		this.otherCardCount = otherCardCount;
	}

	public BigDecimal getOtherCardReturnAmount() {
		return this.otherCardReturnAmount;
	}

	public void setOtherCardReturnAmount(BigDecimal otherCardReturnAmount) {
		this.otherCardReturnAmount = otherCardReturnAmount;
	}

	public Integer getOtherCardReturnCount() {
		return this.otherCardReturnCount;
	}

	public void setOtherCardReturnCount(Integer otherCardReturnCount) {
		this.otherCardReturnCount = otherCardReturnCount;
	}

	public BigDecimal getOtherCardNetAmount() {
		return this.otherCardNetAmount;
	}

	public void setOtherCardNetAmount(BigDecimal otherCardNetAmount) {
		this.otherCardNetAmount = otherCardNetAmount;
	}

	public Integer getOtherCardTransactionCount() {
		return this.otherCardTransactionCount;
	}

	public void setOtherCardTransactionCount(Integer otherCardTransactionCount) {
		this.otherCardTransactionCount = otherCardTransactionCount;
	}

	public String getRegionCode() {
		return this.regionCode;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}

	public String getMerchantType() {
		return this.merchantType;
	}

	public void setMerchantType(String merchantType) {
		this.merchantType = merchantType;
	}

	public String getAgentCode() {
		return this.agentCode;
	}

	public void setAgentCode(String agentCode) {
		this.agentCode = agentCode;
	}

}
