package com.hcmus.model.pojo;
// Generated Nov 29, 2016 3:35:54 PM by Hibernate Tools 3.5.0.Final


import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * MerchantType generated by hbm2java
 */
public class MerchantType implements java.io.Serializable {

	private String merchantType;
	private String description;
	private Set<Merchant> merchants = new HashSet<Merchant>(0);

	public MerchantType() {
	}

	public MerchantType(String merchantType, String description) {
		this.merchantType = merchantType;
		this.description = description;
	}

	public MerchantType(String merchantType, String description, Set<Merchant> merchants) {
		this.merchantType = merchantType;
		this.description = description;
		this.merchants = merchants;
	}

	public String getMerchantType() {
		return this.merchantType;
	}

	public void setMerchantType(String merchantType) {
		this.merchantType = merchantType;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	@JsonIgnore
	public Set<Merchant> getMerchants() {
		return this.merchants;
	}

	public void setMerchants(Set<Merchant> merchants) {
		this.merchants = ORMUtils.initializeAndUnproxy(merchants);
	}

}
