package com.hcmus.model.pojo;
// Generated Nov 29, 2016 3:35:54 PM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;

/**
 * MerchantSummaryQuarterly generated by hbm2java
 */
public class MerchantSummaryQuarterly implements java.io.Serializable {

	//private MerchantSummaryQuarterlyId id;
	private int reportQuarter;
	private int reportYear;
	private String merchantCode;
	private BigDecimal saleAmount;
	private Long saleCount;
	private BigDecimal returnAmount;
	private Long returnCount;
	private BigDecimal netAmount;
	private Long transactionCount;
	private BigDecimal keyedAmount;
	private Long keyedCount;
	private BigDecimal keyedReturnAmount;
	private Long keyedReturnCount;
	private BigDecimal keyedNetAmount;
	private Long keyedTransactionCount;
	private BigDecimal foreignCardAmount;
	private Long foreignCardCount;
	private BigDecimal foreignCardReturnAmount;
	private Long foreignCardReturnCount;
	private BigDecimal foreignCardNetAmount;
	private Long foreignCardTransactionCount;
	private BigDecimal debitCardAmount;
	private Long debitCardCount;
	private BigDecimal debitCardReturnAmount;
	private Long debitCardReturnCount;
	private BigDecimal debitCardNetAmount;
	private Long debitCardTransactionCount;
	private BigDecimal visaCardAmount;
	private Long visaCardCount;
	private BigDecimal visaCardReturnAmount;
	private Long visaCardReturnCount;
	private BigDecimal visaCardNetAmount;
	private Long visaCardTransactionCount;
	private BigDecimal discoverCardAmount;
	private Long discoverCardCount;
	private BigDecimal discoverCardReturnAmount;
	private Long discoverCardReturnCount;
	private BigDecimal discoverCardNetAmount;
	private Long discoverCardTransactionCount;
	private BigDecimal masterCardAmount;
	private Long masterCardCount;
	private BigDecimal masterCardReturnAmount;
	private Long masterCardReturnCount;
	private BigDecimal masterCardNetAmount;
	private Long masterCardTransactionCount;
	private BigDecimal americanExpressAmount;
	private Long americanExpressCount;
	private BigDecimal americanExpressReturnAmount;
	private Long americanExpressReturnCount;
	private BigDecimal americanExpressNetAmount;
	private Long americanExpressTransactionCount;
	private BigDecimal otherCardAmount;
	private Long otherCardCount;
	private BigDecimal otherCardReturnAmount;
	private Long otherCardReturnCount;
	private BigDecimal otherCardNetAmount;
	private Long otherCardTransactionCount;
	private String regionCode;
	private String merchantType;
	private String agentCode;

	public MerchantSummaryQuarterly() {
	}



	public MerchantSummaryQuarterly(int reportQuarter, int reportYear, String merchantCode, BigDecimal saleAmount, Long saleCount,
			BigDecimal returnAmount, Long returnCount, BigDecimal netAmount, Long transactionCount,
			BigDecimal keyedAmount, Long keyedCount, BigDecimal keyedReturnAmount, Long keyedReturnCount,
			BigDecimal keyedNetAmount, Long keyedTransactionCount, BigDecimal foreignCardAmount, Long foreignCardCount,
			BigDecimal foreignCardReturnAmount, Long foreignCardReturnCount, BigDecimal foreignCardNetAmount,
			Long foreignCardTransactionCount, BigDecimal debitCardAmount, Long debitCardCount,
			BigDecimal debitCardReturnAmount, Long debitCardReturnCount, BigDecimal debitCardNetAmount,
			Long debitCardTransactionCount, BigDecimal visaCardAmount, Long visaCardCount,
			BigDecimal visaCardReturnAmount, Long visaCardReturnCount, BigDecimal visaCardNetAmount,
			Long visaCardTransactionCount, BigDecimal discoverCardAmount, Long discoverCardCount,
			BigDecimal discoverCardReturnAmount, Long discoverCardReturnCount, BigDecimal discoverCardNetAmount,
			Long discoverCardTransactionCount, BigDecimal masterCardAmount, Long masterCardCount,
			BigDecimal masterCardReturnAmount, Long masterCardReturnCount, BigDecimal masterCardNetAmount,
			Long masterCardTransactionCount, BigDecimal americanExpressAmount, Long americanExpressCount,
			BigDecimal americanExpressReturnAmount, Long americanExpressReturnCount,
			BigDecimal americanExpressNetAmount, Long americanExpressTransactionCount, BigDecimal otherCardAmount,
			Long otherCardCount, BigDecimal otherCardReturnAmount, Long otherCardReturnCount,
			BigDecimal otherCardNetAmount, Long otherCardTransactionCount, String regionCode, String merchantType,
			String agentCode) {
		this.reportQuarter = reportQuarter;
		this.reportYear = reportYear;
		this.merchantCode = merchantCode;
		this.saleAmount = saleAmount;
		this.saleCount = saleCount;
		this.returnAmount = returnAmount;
		this.returnCount = returnCount;
		this.netAmount = netAmount;
		this.transactionCount = transactionCount;
		this.keyedAmount = keyedAmount;
		this.keyedCount = keyedCount;
		this.keyedReturnAmount = keyedReturnAmount;
		this.keyedReturnCount = keyedReturnCount;
		this.keyedNetAmount = keyedNetAmount;
		this.keyedTransactionCount = keyedTransactionCount;
		this.foreignCardAmount = foreignCardAmount;
		this.foreignCardCount = foreignCardCount;
		this.foreignCardReturnAmount = foreignCardReturnAmount;
		this.foreignCardReturnCount = foreignCardReturnCount;
		this.foreignCardNetAmount = foreignCardNetAmount;
		this.foreignCardTransactionCount = foreignCardTransactionCount;
		this.debitCardAmount = debitCardAmount;
		this.debitCardCount = debitCardCount;
		this.debitCardReturnAmount = debitCardReturnAmount;
		this.debitCardReturnCount = debitCardReturnCount;
		this.debitCardNetAmount = debitCardNetAmount;
		this.debitCardTransactionCount = debitCardTransactionCount;
		this.visaCardAmount = visaCardAmount;
		this.visaCardCount = visaCardCount;
		this.visaCardReturnAmount = visaCardReturnAmount;
		this.visaCardReturnCount = visaCardReturnCount;
		this.visaCardNetAmount = visaCardNetAmount;
		this.visaCardTransactionCount = visaCardTransactionCount;
		this.discoverCardAmount = discoverCardAmount;
		this.discoverCardCount = discoverCardCount;
		this.discoverCardReturnAmount = discoverCardReturnAmount;
		this.discoverCardReturnCount = discoverCardReturnCount;
		this.discoverCardNetAmount = discoverCardNetAmount;
		this.discoverCardTransactionCount = discoverCardTransactionCount;
		this.masterCardAmount = masterCardAmount;
		this.masterCardCount = masterCardCount;
		this.masterCardReturnAmount = masterCardReturnAmount;
		this.masterCardReturnCount = masterCardReturnCount;
		this.masterCardNetAmount = masterCardNetAmount;
		this.masterCardTransactionCount = masterCardTransactionCount;
		this.americanExpressAmount = americanExpressAmount;
		this.americanExpressCount = americanExpressCount;
		this.americanExpressReturnAmount = americanExpressReturnAmount;
		this.americanExpressReturnCount = americanExpressReturnCount;
		this.americanExpressNetAmount = americanExpressNetAmount;
		this.americanExpressTransactionCount = americanExpressTransactionCount;
		this.otherCardAmount = otherCardAmount;
		this.otherCardCount = otherCardCount;
		this.otherCardReturnAmount = otherCardReturnAmount;
		this.otherCardReturnCount = otherCardReturnCount;
		this.otherCardNetAmount = otherCardNetAmount;
		this.otherCardTransactionCount = otherCardTransactionCount;
		this.regionCode = regionCode;
		this.merchantType = merchantType;
		this.agentCode = agentCode;
	}
	public int getReportQuarter() {
		return reportQuarter;
	}

	public void setReportQuarter(int reportQuarter) {
		this.reportQuarter = reportQuarter;
	}

	public int getReportYear() {
		return reportYear;
	}

	public void setReportYear(int reportYear) {
		this.reportYear = reportYear;
	}

	public String getMerchantCode() {
		return merchantCode;
	}

	public void setMerchantCode(String merchantCode) {
		this.merchantCode = merchantCode;
	}
	/*
	public MerchantSummaryQuarterlyId getId() {
		return this.id;
	}

	public void setId(MerchantSummaryQuarterlyId id) {
		this.id = id;
	}
	*/
	public BigDecimal getSaleAmount() {
		return this.saleAmount;
	}

	public void setSaleAmount(BigDecimal saleAmount) {
		this.saleAmount = saleAmount;
	}

	public Long getSaleCount() {
		return this.saleCount;
	}

	public void setSaleCount(Long saleCount) {
		this.saleCount = saleCount;
	}

	public BigDecimal getReturnAmount() {
		return this.returnAmount;
	}

	public void setReturnAmount(BigDecimal returnAmount) {
		this.returnAmount = returnAmount;
	}

	public Long getReturnCount() {
		return this.returnCount;
	}

	public void setReturnCount(Long returnCount) {
		this.returnCount = returnCount;
	}

	public BigDecimal getNetAmount() {
		return this.netAmount;
	}

	public void setNetAmount(BigDecimal netAmount) {
		this.netAmount = netAmount;
	}

	public Long getTransactionCount() {
		return this.transactionCount;
	}

	public void setTransactionCount(Long transactionCount) {
		this.transactionCount = transactionCount;
	}

	public BigDecimal getKeyedAmount() {
		return this.keyedAmount;
	}

	public void setKeyedAmount(BigDecimal keyedAmount) {
		this.keyedAmount = keyedAmount;
	}

	public Long getKeyedCount() {
		return this.keyedCount;
	}

	public void setKeyedCount(Long keyedCount) {
		this.keyedCount = keyedCount;
	}

	public BigDecimal getKeyedReturnAmount() {
		return this.keyedReturnAmount;
	}

	public void setKeyedReturnAmount(BigDecimal keyedReturnAmount) {
		this.keyedReturnAmount = keyedReturnAmount;
	}

	public Long getKeyedReturnCount() {
		return this.keyedReturnCount;
	}

	public void setKeyedReturnCount(Long keyedReturnCount) {
		this.keyedReturnCount = keyedReturnCount;
	}

	public BigDecimal getKeyedNetAmount() {
		return this.keyedNetAmount;
	}

	public void setKeyedNetAmount(BigDecimal keyedNetAmount) {
		this.keyedNetAmount = keyedNetAmount;
	}

	public Long getKeyedTransactionCount() {
		return this.keyedTransactionCount;
	}

	public void setKeyedTransactionCount(Long keyedTransactionCount) {
		this.keyedTransactionCount = keyedTransactionCount;
	}

	public BigDecimal getForeignCardAmount() {
		return this.foreignCardAmount;
	}

	public void setForeignCardAmount(BigDecimal foreignCardAmount) {
		this.foreignCardAmount = foreignCardAmount;
	}

	public Long getForeignCardCount() {
		return this.foreignCardCount;
	}

	public void setForeignCardCount(Long foreignCardCount) {
		this.foreignCardCount = foreignCardCount;
	}

	public BigDecimal getForeignCardReturnAmount() {
		return this.foreignCardReturnAmount;
	}

	public void setForeignCardReturnAmount(BigDecimal foreignCardReturnAmount) {
		this.foreignCardReturnAmount = foreignCardReturnAmount;
	}

	public Long getForeignCardReturnCount() {
		return this.foreignCardReturnCount;
	}

	public void setForeignCardReturnCount(Long foreignCardReturnCount) {
		this.foreignCardReturnCount = foreignCardReturnCount;
	}

	public BigDecimal getForeignCardNetAmount() {
		return this.foreignCardNetAmount;
	}

	public void setForeignCardNetAmount(BigDecimal foreignCardNetAmount) {
		this.foreignCardNetAmount = foreignCardNetAmount;
	}

	public Long getForeignCardTransactionCount() {
		return this.foreignCardTransactionCount;
	}

	public void setForeignCardTransactionCount(Long foreignCardTransactionCount) {
		this.foreignCardTransactionCount = foreignCardTransactionCount;
	}

	public BigDecimal getDebitCardAmount() {
		return this.debitCardAmount;
	}

	public void setDebitCardAmount(BigDecimal debitCardAmount) {
		this.debitCardAmount = debitCardAmount;
	}

	public Long getDebitCardCount() {
		return this.debitCardCount;
	}

	public void setDebitCardCount(Long debitCardCount) {
		this.debitCardCount = debitCardCount;
	}

	public BigDecimal getDebitCardReturnAmount() {
		return this.debitCardReturnAmount;
	}

	public void setDebitCardReturnAmount(BigDecimal debitCardReturnAmount) {
		this.debitCardReturnAmount = debitCardReturnAmount;
	}

	public Long getDebitCardReturnCount() {
		return this.debitCardReturnCount;
	}

	public void setDebitCardReturnCount(Long debitCardReturnCount) {
		this.debitCardReturnCount = debitCardReturnCount;
	}

	public BigDecimal getDebitCardNetAmount() {
		return this.debitCardNetAmount;
	}

	public void setDebitCardNetAmount(BigDecimal debitCardNetAmount) {
		this.debitCardNetAmount = debitCardNetAmount;
	}

	public Long getDebitCardTransactionCount() {
		return this.debitCardTransactionCount;
	}

	public void setDebitCardTransactionCount(Long debitCardTransactionCount) {
		this.debitCardTransactionCount = debitCardTransactionCount;
	}

	public BigDecimal getVisaCardAmount() {
		return this.visaCardAmount;
	}

	public void setVisaCardAmount(BigDecimal visaCardAmount) {
		this.visaCardAmount = visaCardAmount;
	}

	public Long getVisaCardCount() {
		return this.visaCardCount;
	}

	public void setVisaCardCount(Long visaCardCount) {
		this.visaCardCount = visaCardCount;
	}

	public BigDecimal getVisaCardReturnAmount() {
		return this.visaCardReturnAmount;
	}

	public void setVisaCardReturnAmount(BigDecimal visaCardReturnAmount) {
		this.visaCardReturnAmount = visaCardReturnAmount;
	}

	public Long getVisaCardReturnCount() {
		return this.visaCardReturnCount;
	}

	public void setVisaCardReturnCount(Long visaCardReturnCount) {
		this.visaCardReturnCount = visaCardReturnCount;
	}

	public BigDecimal getVisaCardNetAmount() {
		return this.visaCardNetAmount;
	}

	public void setVisaCardNetAmount(BigDecimal visaCardNetAmount) {
		this.visaCardNetAmount = visaCardNetAmount;
	}

	public Long getVisaCardTransactionCount() {
		return this.visaCardTransactionCount;
	}

	public void setVisaCardTransactionCount(Long visaCardTransactionCount) {
		this.visaCardTransactionCount = visaCardTransactionCount;
	}

	public BigDecimal getDiscoverCardAmount() {
		return this.discoverCardAmount;
	}

	public void setDiscoverCardAmount(BigDecimal discoverCardAmount) {
		this.discoverCardAmount = discoverCardAmount;
	}

	public Long getDiscoverCardCount() {
		return this.discoverCardCount;
	}

	public void setDiscoverCardCount(Long discoverCardCount) {
		this.discoverCardCount = discoverCardCount;
	}

	public BigDecimal getDiscoverCardReturnAmount() {
		return this.discoverCardReturnAmount;
	}

	public void setDiscoverCardReturnAmount(BigDecimal discoverCardReturnAmount) {
		this.discoverCardReturnAmount = discoverCardReturnAmount;
	}

	public Long getDiscoverCardReturnCount() {
		return this.discoverCardReturnCount;
	}

	public void setDiscoverCardReturnCount(Long discoverCardReturnCount) {
		this.discoverCardReturnCount = discoverCardReturnCount;
	}

	public BigDecimal getDiscoverCardNetAmount() {
		return this.discoverCardNetAmount;
	}

	public void setDiscoverCardNetAmount(BigDecimal discoverCardNetAmount) {
		this.discoverCardNetAmount = discoverCardNetAmount;
	}

	public Long getDiscoverCardTransactionCount() {
		return this.discoverCardTransactionCount;
	}

	public void setDiscoverCardTransactionCount(Long discoverCardTransactionCount) {
		this.discoverCardTransactionCount = discoverCardTransactionCount;
	}

	public BigDecimal getMasterCardAmount() {
		return this.masterCardAmount;
	}

	public void setMasterCardAmount(BigDecimal masterCardAmount) {
		this.masterCardAmount = masterCardAmount;
	}

	public Long getMasterCardCount() {
		return this.masterCardCount;
	}

	public void setMasterCardCount(Long masterCardCount) {
		this.masterCardCount = masterCardCount;
	}

	public BigDecimal getMasterCardReturnAmount() {
		return this.masterCardReturnAmount;
	}

	public void setMasterCardReturnAmount(BigDecimal masterCardReturnAmount) {
		this.masterCardReturnAmount = masterCardReturnAmount;
	}

	public Long getMasterCardReturnCount() {
		return this.masterCardReturnCount;
	}

	public void setMasterCardReturnCount(Long masterCardReturnCount) {
		this.masterCardReturnCount = masterCardReturnCount;
	}

	public BigDecimal getMasterCardNetAmount() {
		return this.masterCardNetAmount;
	}

	public void setMasterCardNetAmount(BigDecimal masterCardNetAmount) {
		this.masterCardNetAmount = masterCardNetAmount;
	}

	public Long getMasterCardTransactionCount() {
		return this.masterCardTransactionCount;
	}

	public void setMasterCardTransactionCount(Long masterCardTransactionCount) {
		this.masterCardTransactionCount = masterCardTransactionCount;
	}

	public BigDecimal getAmericanExpressAmount() {
		return this.americanExpressAmount;
	}

	public void setAmericanExpressAmount(BigDecimal americanExpressAmount) {
		this.americanExpressAmount = americanExpressAmount;
	}

	public Long getAmericanExpressCount() {
		return this.americanExpressCount;
	}

	public void setAmericanExpressCount(Long americanExpressCount) {
		this.americanExpressCount = americanExpressCount;
	}

	public BigDecimal getAmericanExpressReturnAmount() {
		return this.americanExpressReturnAmount;
	}

	public void setAmericanExpressReturnAmount(BigDecimal americanExpressReturnAmount) {
		this.americanExpressReturnAmount = americanExpressReturnAmount;
	}

	public Long getAmericanExpressReturnCount() {
		return this.americanExpressReturnCount;
	}

	public void setAmericanExpressReturnCount(Long americanExpressReturnCount) {
		this.americanExpressReturnCount = americanExpressReturnCount;
	}

	public BigDecimal getAmericanExpressNetAmount() {
		return this.americanExpressNetAmount;
	}

	public void setAmericanExpressNetAmount(BigDecimal americanExpressNetAmount) {
		this.americanExpressNetAmount = americanExpressNetAmount;
	}

	public Long getAmericanExpressTransactionCount() {
		return this.americanExpressTransactionCount;
	}

	public void setAmericanExpressTransactionCount(Long americanExpressTransactionCount) {
		this.americanExpressTransactionCount = americanExpressTransactionCount;
	}

	public BigDecimal getOtherCardAmount() {
		return this.otherCardAmount;
	}

	public void setOtherCardAmount(BigDecimal otherCardAmount) {
		this.otherCardAmount = otherCardAmount;
	}

	public Long getOtherCardCount() {
		return this.otherCardCount;
	}

	public void setOtherCardCount(Long otherCardCount) {
		this.otherCardCount = otherCardCount;
	}

	public BigDecimal getOtherCardReturnAmount() {
		return this.otherCardReturnAmount;
	}

	public void setOtherCardReturnAmount(BigDecimal otherCardReturnAmount) {
		this.otherCardReturnAmount = otherCardReturnAmount;
	}

	public Long getOtherCardReturnCount() {
		return this.otherCardReturnCount;
	}

	public void setOtherCardReturnCount(Long otherCardReturnCount) {
		this.otherCardReturnCount = otherCardReturnCount;
	}

	public BigDecimal getOtherCardNetAmount() {
		return this.otherCardNetAmount;
	}

	public void setOtherCardNetAmount(BigDecimal otherCardNetAmount) {
		this.otherCardNetAmount = otherCardNetAmount;
	}

	public Long getOtherCardTransactionCount() {
		return this.otherCardTransactionCount;
	}

	public void setOtherCardTransactionCount(Long otherCardTransactionCount) {
		this.otherCardTransactionCount = otherCardTransactionCount;
	}

	public String getRegionCode() {
		return this.regionCode;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}

	public String getMerchantType() {
		return this.merchantType;
	}

	public void setMerchantType(String merchantType) {
		this.merchantType = merchantType;
	}

	public String getAgentCode() {
		return this.agentCode;
	}

	public void setAgentCode(String agentCode) {
		this.agentCode = agentCode;
	}

}
