package com.hcmus.model.pojo;
// Generated Nov 29, 2016 3:35:54 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Merchant generated by hbm2java
 */
public class Merchant implements java.io.Serializable {
	private String MerchantCode;
	private String AgentCode;
	private String CityCode;
	private int BackEndProcessor;
	private String MerchantType;
	private String MerchantName;
	private Character Status;
	private String Owner;
	private String Address1;
	private String Address2;
	private String Address3;
	private Integer Zip;
	private String Phone;
	private String Fax;
	private String Email;
	private Date ApprovalDate;
	private Date CloseDate;
	private String BankCardDba;
	private Date FirstActiveDate;
	private Date LastActiveDate;
	private String CityName;
	private String RegionCode;
	private String RegionName;
	private String Description;
	private Agent AGENT;
	private City CITY;
	private Processor PROCESSOR;
	private MerchantType MERCHANTTYPE;
	private Set<TransactionDetail> TRANSACTIONDETAILS = new HashSet<TransactionDetail>(0);
	private Set<Retrival> RETRIVALS = new HashSet<Retrival>(0);

	public Merchant() {
	}

	public Merchant(String merchantCode,String agentCode, String cityCode, int backEndProcessor, String merchantType,
			String merchantName, Character status, String owner, String address1,
			String address2, String address3, Integer zip, String phone, String fax, String email,
			Date approvalDate, Date closeDate, String bankCardDba, Date firstActiveDate, Date lastActiveDate,
			String cityName, String regionCode, String regionName, String description, Agent AGENT, City CITY,
			Processor PROCESSOR, MerchantType MERCHANTTYPE, Set<TransactionDetail> TRANSACTIONDETAILS, Set<Retrival> RETRIVALS ) {
		this.MerchantCode = merchantCode;
		this.AgentCode = agentCode;
		this.CityCode = cityCode;
		this.BackEndProcessor = backEndProcessor;
		this.MerchantType = merchantType;
		this.MerchantName = merchantName;
		this.Status = status;
		this.Owner = owner;
		this.Address1 = address1;
		this.Address2 = address2;
		this.Address3 = address3;
		this.Zip = zip;
		this.Phone = phone;
		this.Fax = fax;
		this.Email = email;
		this.ApprovalDate = approvalDate;
		this.CloseDate = closeDate;
		this.BankCardDba = bankCardDba;
		this.FirstActiveDate = firstActiveDate;
		this.LastActiveDate = lastActiveDate;
		this.CityName = cityName;
		this.RegionCode = regionCode;
		this.RegionName = regionName;
		this.Description = description;
		this.AGENT = AGENT;
		this.CITY = CITY;
		this.MERCHANTTYPE = MERCHANTTYPE;
		this.PROCESSOR = PROCESSOR;
		this.TRANSACTIONDETAILS = TRANSACTIONDETAILS;
		this.RETRIVALS = RETRIVALS;
		
	}
	@JsonProperty("MerchantCode")
	
	public String getMerchantCode() {
		return this.MerchantCode;
	}

	public void setMerchantCode(String merchantCode) {
		this.MerchantCode = merchantCode;
	}
	@JsonProperty("AgentCode")
	public String  getAgentCode() {
		return this.AgentCode;
	}
	
	public void setAgentCode(String agentCode) {
		this.AgentCode = agentCode;
	}
	@JsonProperty("CityCode")
	public String getCityCode() {
		return this.CityCode;
	}
	
	public void setCityCode(String cityCode) {
		this.CityCode = cityCode;
	}
	@JsonProperty("BackEndProcessor")
	public int getBackEndProcessor() {
		return this.BackEndProcessor;
	}

	public void setBackEndProcessor(int backEndProcessor) {
		this.BackEndProcessor = backEndProcessor;
	}
	@JsonProperty("MerchantType")
	public String getMerchantType() {
		return this.MerchantType;
	}
	
	public void setMerchantType(String merchantType) {
		this.MerchantType = merchantType;
	}
	@JsonProperty("MerchantName")
	public String getMerchantName() {
		return this.MerchantName;
	}

	public void setMerchantName(String merchantName) {
		this.MerchantName = merchantName;
	}
	@JsonProperty("Status")
	public Character getStatus() {
		return this.Status;
	}

	public void setStatus(Character status) {
		this.Status = status;
	}
	@JsonProperty("Owner")
	public String getOwner() {
		return this.Owner;
	}

	public void setOwner(String owner) {
		this.Owner = owner;
	}
	@JsonProperty("Address1")
	public String getAddress1() {
		return this.Address1;
	}
	
	public void setAddress1(String address1) {
		this.Address1 = address1;
	}
	@JsonProperty("Address2")
	public String getAddress2() {
		return this.Address2;
	}

	public void setAddress2(String address2) {
		this.Address2 = address2;
	}
	@JsonProperty("Address3")
	public String getAddress3() {
		return this.Address3;
	}

	public void setAddress3(String address3) {
		this.Address3 = address3;
	}
	@JsonProperty("Zip")
	public Integer getZip() {
		return this.Zip;
	}

	public void setZip(Integer zip) {
		this.Zip = zip;
	}
	@JsonProperty("Phone")
	public String getPhone() {
		return this.Phone;
	}

	public void setPhone(String phone) {
		this.Phone = phone;
	}
	@JsonProperty("Fax")
	public String getFax() {
		return this.Fax;
	}

	public void setFax(String fax) {
		this.Fax = fax;
	}
	@JsonProperty("Email")
	public String getEmail() {
		return this.Email;
	}
	
	public void setEmail(String email) {
		this.Email = email;
	}
	@JsonProperty("ApprovalDate")
	public Date getApprovalDate() {
		return this.ApprovalDate;
	}

	public void setApprovalDate(Date approvalDate) {
		this.ApprovalDate = approvalDate;
	}
	@JsonProperty("CloseDate")
	public Date getCloseDate() {
		return this.CloseDate;
	}

	public void setCloseDate(Date closeDate) {
		this.CloseDate = closeDate;
	}
	@JsonProperty("BankCardDBA")
	public String getBankCardDba() {
		return this.BankCardDba;
	}

	public void setBankCardDba(String bankCardDba) {
		this.BankCardDba = bankCardDba;
	}
	@JsonProperty("FirstActiveDate")
	public Date getFirstActiveDate() {
		return this.FirstActiveDate;
	}

	public void setFirstActiveDate(Date firstActiveDate) {
		this.FirstActiveDate = firstActiveDate;
	}
	@JsonProperty("LastActiveDate")
	public Date getLastActiveDate() {
		return this.LastActiveDate;
	}

	public void setLastActiveDate(Date lastActiveDate) {
		this.LastActiveDate = lastActiveDate;
	}
	@JsonProperty("CityName")
	public String getCityName() {
		return this.CityName;
	}

	public void setCityName(String cityName) {
		this.CityName = cityName;
	}
	@JsonProperty("RegionCode")
	public String getRegionCode() {
		return this.RegionCode;
	}
	
	public void setRegionCode(String regionCode) {
		this.RegionCode = regionCode;
	}
	@JsonProperty("RegionName")
	public String getRegionName() {
		return this.RegionName;
	}
		
	public void setRegionName(String regionName) {
		this.RegionName = regionName;
	}
	@JsonProperty("Description")
	public String getDescription() {
		return this.Description;
	}

	public void setDescription(String description) {
		this.Description = description;
	}
	//@JsonBackReference
	//@JsonManagedReference
	//@JsonIgnore
	@JsonProperty("AGENT")
	public Agent getAGENT() {
		//this.AGENT = EntityService.initializeAndUnproxy(AGENT);
		return this.AGENT;
	}
	public void setAGENT(Agent AGENT) {
		this.AGENT = ORMUtils.initializeAndUnproxy(AGENT);
	}
	@JsonProperty("CITY")	
	public City getCITY() {
		return CITY;
	}

	public void setCITY(City CITY) {
		this.CITY = ORMUtils.initializeAndUnproxy(CITY);
	}
	@JsonProperty("PROCESSOR")
	public Processor getPROCESSOR() {
		return PROCESSOR;
	}

	public void setPROCESSOR(Processor PROCESSOR) {
		this.PROCESSOR = ORMUtils.initializeAndUnproxy(PROCESSOR);;
	}
	@JsonProperty("TRANSACTION_DETAIL")
	public Set<TransactionDetail> getTRANSACTIONDETAILS() {
		return this.TRANSACTIONDETAILS;
	}

	public void setTRANSACTIONDETAILS(Set<TransactionDetail> TRANSACTIONDETAILS) {
		this.TRANSACTIONDETAILS = ORMUtils.initializeAndUnproxy(TRANSACTIONDETAILS);//TRANSACTIONDETAILS;
	}
	@JsonProperty("RETRIVAL")
	public Set<Retrival> getRETRIVALS() {
		return this.RETRIVALS;
	}

	public void setRETRIVALS(Set<Retrival> RETRIVALS) {
		this.RETRIVALS = ORMUtils.initializeAndUnproxy(RETRIVALS);
	}
	@JsonProperty("MERCHANT_TYPE")
	public void setMERCHANTTYPE(MerchantType MERCHANTTYPE) {
		this.MERCHANTTYPE = ORMUtils.initializeAndUnproxy(MERCHANTTYPE);
	}
	public MerchantType getMERCHANTTYPE() {
		return this.MERCHANTTYPE;
	}
	

}
