package com.hcmus.model.pojo;
// Generated Nov 29, 2016 3:35:54 PM by Hibernate Tools 3.5.0.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Processor generated by hbm2java
 */
public class Processor implements java.io.Serializable {

	private int id;
	private String processorCode;
	private String processorName;
	private Character status;
	private Date approvalDate;
	private Date closeDate;
	private Date firstActiveDate;
	private Date lastActiveDate;
	private Set<Merchant> merchants = new HashSet<Merchant>(0);

	public Processor() {
	}

	public Processor(int id, String processorCode, String processorName) {
		this.id = id;
		this.processorCode = processorCode;
		this.processorName = processorName;
	}

	public Processor(int id, String processorCode, String processorName, Character status, Date approvalDate,
			Date closeDate, Date firstActiveDate, Date lastActiveDate, Set<Merchant> merchants) {
		this.id = id;
		this.processorCode = processorCode;
		this.processorName = processorName;
		this.status = status;
		this.approvalDate = approvalDate;
		this.closeDate = closeDate;
		this.firstActiveDate = firstActiveDate;
		this.lastActiveDate = lastActiveDate;
		this.merchants = merchants;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getProcessorCode() {
		return this.processorCode;
	}

	public void setProcessorCode(String processorCode) {
		this.processorCode = processorCode;
	}

	public String getProcessorName() {
		return this.processorName;
	}

	public void setProcessorName(String processorName) {
		this.processorName = processorName;
	}

	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	public Date getApprovalDate() {
		return this.approvalDate;
	}

	public void setApprovalDate(Date approvalDate) {
		this.approvalDate = approvalDate;
	}

	public Date getCloseDate() {
		return this.closeDate;
	}

	public void setCloseDate(Date closeDate) {
		this.closeDate = closeDate;
	}

	public Date getFirstActiveDate() {
		return this.firstActiveDate;
	}

	public void setFirstActiveDate(Date firstActiveDate) {
		this.firstActiveDate = firstActiveDate;
	}

	public Date getLastActiveDate() {
		return this.lastActiveDate;
	}

	public void setLastActiveDate(Date lastActiveDate) {
		this.lastActiveDate = lastActiveDate;
	}
	@JsonIgnore
	public Set<Merchant> getMerchants() {
		return this.merchants;
	}

	public void setMerchants(Set<Merchant> merchants) {
		this.merchants = ORMUtils.initializeAndUnproxy(merchants);
	}

}
