package com.hcmus.model.pojo;
// Generated Nov 29, 2016 3:35:54 PM by Hibernate Tools 3.5.0.Final


import java.util.HashSet;
import java.util.Set;

import org.springframework.transaction.annotation.Transactional;

/**
 * Region generated by hbm2java
 */
@Transactional
public class Region implements java.io.Serializable {
	private String regionCode;
	private String countryCode;
	private String regionName;
	private Country country;
	private Set<City> cities = new HashSet<City>(0);

	public Region() {
	}

	public Region(String regionCode, Country country, String regionName, Set<City> cities) {
		this.regionCode = regionCode;
		this.country = country;
		this.regionName = regionName;
		this.cities = cities;
	}

	public String getRegionCode() {
		return this.regionCode;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}

	public String getRegionName() {
		return this.regionName;
	}

	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}
	public String getCountryCode() {
		return countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	public Country getCountry() {
		return country;
	}

	public void setCountry(Country country) {
		this.country = ORMUtils.initializeAndUnproxy(country);
	}
	public Set<City> getCities() {
		return this.cities;
	}

	public void setCities(Set<City> cities) {
		this.cities = ORMUtils.initializeAndUnproxy(cities);
	}

}
