package com.hcmus.model.pojo;
// Generated Nov 29, 2016 3:34:03 PM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * RetrivalInvalid generated by hbm2java
 */
@Entity
@Table(name = "RETRIVAL_INVALID")
public class RetrivalInvalid implements java.io.Serializable {

	private String retrivalCode;
	private String accountNumber;
	private String merchantCode;
	private String transactionCode;
	private Date transactionDate;
	private Date reportDate;
	private BigDecimal amout;
	private String errorMessage;

	public RetrivalInvalid() {
	}

	public RetrivalInvalid(String retrivalCode, String merchantCode) {
		this.retrivalCode = retrivalCode;
		this.merchantCode = merchantCode;
	}

	public RetrivalInvalid(String retrivalCode, String accountNumber, String merchantCode, String transactionCode,
			Date transactionDate, Date reportDate, BigDecimal amout, String errorMessage) {
		this.retrivalCode = retrivalCode;
		this.accountNumber = accountNumber;
		this.merchantCode = merchantCode;
		this.transactionCode = transactionCode;
		this.transactionDate = transactionDate;
		this.reportDate = reportDate;
		this.amout = amout;
		this.errorMessage = errorMessage;
	}

	@JsonProperty("RetrivalCode")

	@Column(name = "RetrivalCode", unique = true, nullable = false, length = 10)
	public String getRetrivalCode() {
		return this.retrivalCode;
	}

	public void setRetrivalCode(String retrivalCode) {
		this.retrivalCode = retrivalCode;
	}

	@Column(name = "AccountNumber", length = 20)
	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	@Column(name = "MerchantCode", nullable = false, length = 10)
	public String getMerchantCode() {
		return this.merchantCode;
	}

	public void setMerchantCode(String merchantCode) {
		this.merchantCode = merchantCode;
	}

	@Column(name = "TransactionCode", length = 20)
	public String getTransactionCode() {
		return this.transactionCode;
	}

	public void setTransactionCode(String transactionCode) {
		this.transactionCode = transactionCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TransactionDate", length = 10)
	public Date getTransactionDate() {
		return this.transactionDate;
	}

	public void setTransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ReportDate", length = 10)
	public Date getReportDate() {
		return this.reportDate;
	}

	public void setReportDate(Date reportDate) {
		this.reportDate = reportDate;
	}

	@Column(name = "Amout", scale = 4)
	public BigDecimal getAmout() {
		return this.amout;
	}

	public void setAmout(BigDecimal amout) {
		this.amout = amout;
	}

	@Column(name = "ErrorMessage")
	public String getErrorMessage() {
		return this.errorMessage;
	}

	public void setErrorMessage(String errorMessage) {
		this.errorMessage = errorMessage;
	}

}
