package com.hcmus.model.pojo;
// Generated Nov 29, 2016 3:35:54 PM by Hibernate Tools 3.5.0.Final

//import java.io.String;
import java.math.BigDecimal;
import java.util.Date;



/**
 * TransactionDetail generated by hbm2java
 */
public class TransactionDetail implements java.io.Serializable {
	private String transactionCode;
	private Date reportDate;
	private String accountNumber;
	private String transactionTypeCode;
	private String terminalNumber;
	private int fileSource;
	private Long batchNumber;
	private Date expirationDate;
	private String cardTypeCode;
	private BigDecimal transactionAmount;
	private Date transactionDate;
	private Date transactionTime;
	private Boolean keyedEntry;
	private String authorizationNumber;
	private Date reportTime;
	private String description;
	private String firstTwelveAccountNumber;
	private String regionCode;
	private String merchantType;
	private String agentCode;
	private String merchantCode;
	private Merchant merchant;
	private Card	card;
	private TransactionType transactionType;

	public TransactionDetail() {
	}

	public TransactionDetail(Date reportDate, String transactionCode, String accountNumber, String transactionTypeCode,
			String terminalNumber, int fileSource, Long batchNumber, Date expirationDate, String cardTypeCode,
			BigDecimal transactionAmount, Date transactionDate, Date transactionTime, Boolean keyedEntry,
			String authorizationNumber, Date reportTime, String description, String firstTwelveAccountNumber,
			String regionCode, String merchantType, String agentCode,String merchantCode, Merchant merchant, Card card, TransactionType transactionType ) {
		//this.id = id;
		this.accountNumber = accountNumber;
		this.transactionTypeCode = transactionTypeCode;
		this.terminalNumber = terminalNumber;
		this.fileSource = fileSource;
		this.batchNumber = batchNumber;
		this.expirationDate = expirationDate;
		this.cardTypeCode = cardTypeCode;
		this.transactionAmount = transactionAmount;
		this.transactionDate = transactionDate;
		this.transactionTime = transactionTime;
		this.keyedEntry = keyedEntry;
		this.authorizationNumber = authorizationNumber;
		this.reportTime = reportTime;
		this.description = description;
		this.firstTwelveAccountNumber = firstTwelveAccountNumber;
		this.regionCode = regionCode;
		this.merchantType = merchantType;
		this.agentCode = agentCode;
		this.merchantCode = merchantCode;
		this.card = card;
		this.merchant = merchant;
		this.transactionType = transactionType;
	}
	/*
	public TransactionDetailId getId() {
		return this.id;
	}

	public void setId(TransactionDetailId id) {
		this.id = id;
	}
	*/
	public String getTransactionCode() {
		return transactionCode;
	}

	public void setTransactionCode(String transactionCode) {
		this.transactionCode = transactionCode;
	}

	public Date getReportDate() {
		return reportDate;
	}

	public void setReportDate(Date reportDate) {
		this.reportDate = reportDate;
	}
	public String getAccountNumber() {
		return accountNumber;
	}

	

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	
	public String getTransactionTypeCode() {
		return this.transactionTypeCode;
	}

	public void setTransactionTypeCode(String transactionTypeCode) {
		this.transactionTypeCode = transactionTypeCode;
	}

	public String getTerminalNumber() {
		return this.terminalNumber;
	}

	public void setTerminalNumber(String terminalNumber) {
		this.terminalNumber = terminalNumber;
	}

	public int getFileSource() {
		return this.fileSource;
	}

	public void setFileSource(int fileSource) {
		this.fileSource = fileSource;
	}

	public Long getBatchNumber() {
		return this.batchNumber;
	}

	public void setBatchNumber(Long batchNumber) {
		this.batchNumber = batchNumber;
	}

	public Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	public String getCardTypeCode() {
		return this.cardTypeCode;
	}

	public void setCardTypeCode(String cardTypeCode) {
		this.cardTypeCode = cardTypeCode;
	}

	public BigDecimal getTransactionAmount() {
		return this.transactionAmount;
	}

	public void setTransactionAmount(BigDecimal transactionAmount) {
		this.transactionAmount = transactionAmount;
	}

	public Date getTransactionDate() {
		return this.transactionDate;
	}

	public void setTransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	public Date getTransactionTime() {
		return this.transactionTime;
	}

	public void setTransactionTime(Date transactionTime) {
		this.transactionTime = transactionTime;
	}

	public Boolean getKeyedEntry() {
		return this.keyedEntry;
	}

	public void setKeyedEntry(Boolean keyedEntry) {
		this.keyedEntry = keyedEntry;
	}

	public String getAuthorizationNumber() {
		return this.authorizationNumber;
	}

	public void setAuthorizationNumber(String authorizationNumber) {
		this.authorizationNumber = authorizationNumber;
	}

	public Date getReportTime() {
		return this.reportTime;
	}

	public void setReportTime(Date reportTime) {
		this.reportTime = reportTime;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getFirstTwelveAccountNumber() {
		return this.firstTwelveAccountNumber;
	}

	public void setFirstTwelveAccountNumber(String firstTwelveAccountNumber) {
		this.firstTwelveAccountNumber = firstTwelveAccountNumber;
	}

	public String getRegionCode() {
		return this.regionCode;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}

	public String getMerchantType() {
		return this.merchantType;
	}

	public void setMerchantType(String merchantType) {
		this.merchantType = merchantType;
	}

	public String getAgentCode() {
		return this.agentCode;
	}

	public void setAgentCode(String agentCode) {
		this.agentCode = agentCode;
	}
	public String getMerchantCode() {
		return merchantCode;
	}

	public void setMerchantCode(String merchantCode) {
		this.merchantCode = merchantCode;
	}
	public Card getCard() {
		return card;
	}

	public void setCard(Card card) {
		this.card = ORMUtils.initializeAndUnproxy(card);
	}
	
	public TransactionType getTransactionType() {
		return transactionType;
	}

	public void setTransactionType(TransactionType transactionType) {
		this.transactionType = ORMUtils.initializeAndUnproxy(transactionType);
	}
	public Merchant getMerchant() {
		return this.merchant;
	}

	public void setMerchant(Merchant merchant) {
		this.merchant = ORMUtils.initializeAndUnproxy(merchant);
	}
	
}
