package com.hcmus.model.pojo;
// Generated Nov 29, 2016 3:35:54 PM by Hibernate Tools 3.5.0.Final


import java.util.HashSet;
import java.util.Set;

/**
 * TransactionType generated by hbm2java
 */
public class TransactionType implements java.io.Serializable {

	private String transactionTypeCode;
	private String description;
	private Set<TransactionDetail> transactionDetails = new HashSet<TransactionDetail>(0);

	public TransactionType() {
	}


	public TransactionType(String transactionTypeCode, String description,
			Set<TransactionDetail> transactionDetails) {
		this.transactionTypeCode = transactionTypeCode;
		this.description = description;
		this.transactionDetails = transactionDetails;
	}

	public String getTransactionTypeCode() {
		return this.transactionTypeCode;
	}

	public void setTransactionTypeCode(String transactionTypeCode) {
		this.transactionTypeCode = transactionTypeCode;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<TransactionDetail> getTransactionDetails() {
		return this.transactionDetails;
	}

	public void setTransactionDetails(Set<TransactionDetail> transactionDetails) {
		this.transactionDetails = ORMUtils.initializeAndUnproxy(transactionDetails);
	}

}
