package com.hcmus.model.pojo;
// Generated Nov 29, 2016 3:35:54 PM by Hibernate Tools 3.5.0.Final

//import java.io.String;
import java.math.BigDecimal;
import java.util.Date;

/**
 * TransactionDetailInvalid generated by hbm2java
 */
public class TransactionDetailInvalid implements java.io.Serializable {

	private String transactionCode;
	private Date reportDate;
	private String merchantCode;
	private String terminalNumber;
	private int fileSource;
	private Long batchNumber;
	private Date expirationDate;
	private String cardtypeCode;
	private BigDecimal transactionAmount;
	private Date transactionDate;
	private Date transactionTime;
	private Boolean keyedEntry;
	private String authorizationNumber;
	private Date reportTime;
	private String description;
	private String accountNumber;
	private String firstTwelveAccountNumber;
	private String transactionTypeCode;
	private String regionCode;
	private String merchantType;
	private String agentCode;
	private String errorMessage;

	public TransactionDetailInvalid() {
	}


	public TransactionDetailInvalid(String transactionCode, Date reportDate, String merchantCode, String terminalNumber,
			int fileSource, Long batchNumber, Date expirationDate, String cardtypeCode, BigDecimal transactionAmount,
			Date transactionDate, Date transactionTime, Boolean keyedEntry, String authorizationNumber, Date reportTime,
			String description, String accountNumber, String firstTwelveAccountNumber, String transactionTypeCode,
			String regionCode, String merchantType, String agentCode, String errorMessage) {
		//this.id = id;
		this.transactionCode = transactionCode;
		this.reportDate = reportDate;
		this.merchantCode = merchantCode;
		this.terminalNumber = terminalNumber;
		this.fileSource = fileSource;
		this.batchNumber = batchNumber;
		this.expirationDate = expirationDate;
		this.cardtypeCode = cardtypeCode;
		this.transactionAmount = transactionAmount;
		this.transactionDate = transactionDate;
		this.transactionTime = transactionTime;
		this.keyedEntry = keyedEntry;
		this.authorizationNumber = authorizationNumber;
		this.reportTime = reportTime;
		this.description = description;
		this.accountNumber = accountNumber;
		this.firstTwelveAccountNumber = firstTwelveAccountNumber;
		this.transactionTypeCode = transactionTypeCode;
		this.regionCode = regionCode;
		this.merchantType = merchantType;
		this.agentCode = agentCode;
		this.errorMessage = errorMessage;
	}

	/*public TransactionDetailInvalidId getId() {
		return this.id;
	}

	public void setId(TransactionDetailInvalidId id) {
		this.id = id;
	}
	*/
	public String getTransactionCode() {
		return transactionCode;
	}

	public void setTransactionCode(String transactionCode) {
		this.transactionCode = transactionCode;
	}

	public Date getReportDate() {
		return reportDate;
	}

	public void setReportDate(Date reportDate) {
		this.reportDate = reportDate;
	}

	public String getMerchantCode() {
		return this.merchantCode;
	}

	public void setMerchantCode(String merchantCode) {
		this.merchantCode = merchantCode;
	}

	public String getTerminalNumber() {
		return this.terminalNumber;
	}

	public void setTerminalNumber(String terminalNumber) {
		this.terminalNumber = terminalNumber;
	}

	public int getFileSource() {
		return this.fileSource;
	}

	public void setFileSource(int fileSource) {
		this.fileSource = fileSource;
	}

	public Long getBatchNumber() {
		return this.batchNumber;
	}

	public void setBatchNumber(Long batchNumber) {
		this.batchNumber = batchNumber;
	}

	public Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	public String getCardtypeCode() {
		return this.cardtypeCode;
	}

	public void setCardtypeCode(String cardtypeCode) {
		this.cardtypeCode = cardtypeCode;
	}

	public BigDecimal getTransactionAmount() {
		return this.transactionAmount;
	}

	public void setTransactionAmount(BigDecimal transactionAmount) {
		this.transactionAmount = transactionAmount;
	}

	public Date getTransactionDate() {
		return this.transactionDate;
	}

	public void setTransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	public Date getTransactionTime() {
		return this.transactionTime;
	}

	public void setTransactionTime(Date transactionTime) {
		this.transactionTime = transactionTime;
	}

	public Boolean getKeyedEntry() {
		return this.keyedEntry;
	}

	public void setKeyedEntry(Boolean keyedEntry) {
		this.keyedEntry = keyedEntry;
	}

	public String getAuthorizationNumber() {
		return this.authorizationNumber;
	}

	public void setAuthorizationNumber(String authorizationNumber) {
		this.authorizationNumber = authorizationNumber;
	}

	public Date getReportTime() {
		return this.reportTime;
	}

	public void setReportTime(Date reportTime) {
		this.reportTime = reportTime;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	public String getFirstTwelveAccountNumber() {
		return this.firstTwelveAccountNumber;
	}

	public void setFirstTwelveAccountNumber(String firstTwelveAccountNumber) {
		this.firstTwelveAccountNumber = firstTwelveAccountNumber;
	}

	public String getTransactionTypeCode() {
		return this.transactionTypeCode;
	}

	public void setTransactionTypeCode(String transactionTypeCode) {
		this.transactionTypeCode = transactionTypeCode;
	}

	public String getRegionCode() {
		return this.regionCode;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}

	public String getMerchantType() {
		return this.merchantType;
	}

	public void setMerchantType(String merchantType) {
		this.merchantType = merchantType;
	}

	public String getAgentCode() {
		return this.agentCode;
	}

	public void setAgentCode(String agentCode) {
		this.agentCode = agentCode;
	}

	public String getErrorMessage() {
		return this.errorMessage;
	}

	public void setErrorMessage(String errorMessage) {
		this.errorMessage = errorMessage;
	}

}
