package com.hcmus.model.pojo;
// Generated Nov 29, 2016 3:35:54 PM by Hibernate Tools 3.5.0.Final

/**
 * UserInformation generated by hbm2java
 */
public class UserInformation implements java.io.Serializable {

	private String userName;
	private String password;
	private char userType;
	private char status;

	public UserInformation() {
	}

	public UserInformation(String userName, String password, char userType, char status) {
		this.userName = userName;
		this.password = password;
		this.userType = userType;
		this.status = status;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public char getUserType() {
		return this.userType;
	}

	public void setUserType(char userType) {
		this.userType = userType;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

}
